"""Add timelines model

Revision ID: 7421374e2551
Revises: 23c4b0bf13bf
Create Date: 2020-06-02 17:09:48.068304

"""

# revision identifiers, used by Alembic.
revision = '7421374e2551'
down_revision = '23c4b0bf13bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(), nullable=True),
    sa.Column('summary', sa.Unicode(), nullable=True),
    sa.Column('entities', sa.ARRAY(sa.Unicode()), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_collection_id'), 'timeline', ['collection_id'], unique=False)
    op.create_index(op.f('ix_timeline_role_id'), 'timeline', ['role_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_role_id'), table_name='timeline')
    op.drop_index(op.f('ix_timeline_collection_id'), table_name='timeline')
    op.drop_table('timeline')
    # ### end Alembic commands ###
