"""empty message

Revision ID: 814647dcb345
Revises: 2b478162b2b7
Create Date: 2020-02-17 18:02:43.403079

"""

# revision identifiers, used by Alembic.
revision = '814647dcb345'
down_revision = '2b478162b2b7'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timeline',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.Unicode(), nullable=True),
    sa.Column('summary', sa.Unicode(), nullable=True),
    sa.Column('entities', sa.ARRAY(sa.Unicode()), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('collection_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['collection_id'], ['collection.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_collection_id'), 'timeline', ['collection_id'], unique=False)
    op.create_index(op.f('ix_timeline_role_id'), 'timeline', ['role_id'], unique=False)
    op.drop_table('balkhash_collection_1')
    op.drop_column('diagram', 'data')
    op.alter_column('role', 'is_muted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'is_muted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.add_column('diagram', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_table('balkhash_collection_1',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fragment', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('schema', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.UniqueConstraint('id', 'fragment', name='balkhash_collection_1_id_fragment_key')
    )
    op.drop_index(op.f('ix_timeline_role_id'), table_name='timeline')
    op.drop_index(op.f('ix_timeline_collection_id'), table_name='timeline')
    op.drop_table('timeline')
    # ### end Alembic commands ###
